# Generated by Django 5.2.16 on 2026-07-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('highway', models.CharField(blank=True, default='', max_length=60)),
                ('coordinates', models.JSONField()),
            ],
            options={
                'verbose_name': 'Road Segment',
                'verbose_name_plural': 'Road Segments',
                'ordering': ['id'],
            },
        ),
    ]
