# Generated by Django 5.2.16 on 2026-07-27 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_student_admission_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['admission_number'], 'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterField(
            model_name='studentlocation',
            name='name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
