# Generated by Django 5.2.16 on 2026-08-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False, help_text='Check to open student login. Uncheck to close it.', verbose_name='Login Open?')),
                ('note_message', models.TextField(default='Student login is currently closed. Please check back later or contact support.', help_text='Message displayed to students when login is closed.', verbose_name='Notice Message')),
                ('bypass_emails', models.TextField(blank=True, default='', help_text='Enter emails (one per line or comma-separated) allowed to log in even when login is closed.', verbose_name='Bypass Emails')),
            ],
            options={
                'verbose_name': 'Login Configuration',
                'verbose_name_plural': 'Login Configuration',
            },
        ),
    ]
